# Site settings
title: Bewater Blog
SEOTitle: Bewater的博客 | Bewater Blog
header-img: img/home-bg.jpg
email: ifreesky1988@gmail.com
description: "Bewater Blog"
keyword: "Bewater的博客 | Bewater Blog | Android"
url: "http://beawaters.com"              # Bewater host, for absolute URL
baseurl: ""         # for example, '/blog' if Bewater blog hosted on 'host/blog'

#beawaters.com/img/favicon.ico

# SNS settings
RSS: false
weibo_username:     bewater暂未开通
zhihu_username:     bewater暂未开通
github_username:    bewater暂未开通
#twitter_username:  bewater暂未开通
facebook_username:  bewater暂未开通



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: beawaters
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 02a466052edda94895e8a536562977fe
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: beawaters.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "实实在在做人、踏踏实实做事，少点自大装逼，多点谦虚真诚"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Bewater Blog",
        href: "http://beawaters.com"
    },{
        title: "Bruce Lee",
        href: "#"
    },{
        title: "Steve Jobs",
        href: "#"
    },{
        title: "Jack Ma",
        href: "#"
    }
]
